<?php $products = $this->getProductCollection();
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
$type = 'widget-product-grid';
$image = 'category_page_grid';
?>
<div class="block product-list-block <?php if($this->getData('type_list')): ?><?php echo $this->getData('type_list') ?><?php endif ?>">
	<?php if($this->getData('title')): ?>
		<div class="block-title">
			<h3 class="title"><span><?php echo $this->getData('title') ?></span></h3>
		</div>
	<?php endif ?>
	<?php if(count($products)>0): ?>
		<div class="block-content row">
			<?php $i = 0; foreach($products as $_product): $i++;?>
				<?php	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$productModel = $objectManager->create('Magento\Catalog\Model\Product');
						$_product = $productModel->load($_product->getId()); ?>
				<?php $_itemNameStripped = $block->stripTags($_product->getName(), null, true); ?>
				<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
					$size = $themeHelper->getImageSize();
					$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();  ?>
				<div class="product-content col-md-12 col-sm-4 col-xs-12 <?php if($i % 2 == 1): ?>row-2sm-first<?php endif ?>">
					<div class="product-top">
						<a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
							<img src="<?php echo $productImage; ?>" alt="<?php echo $_itemNameStripped ?>" class="img-responsive"/>
						</a>
					</div>
					<div class="product-details">
						<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_product->getName() ?></a></h6>
						<?php echo $block->getReviewsSummaryHtml($_product, false, true)?>
						<?php  echo $block->getProductPrice($_product) ?>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	<?php else: ?>
		<div class="alert alert-danger"><?php echo __('No product to show'); ?></div>
	<?php endif ?>
</div>