<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magento\Sales\Block\Order\View*/?>

<?php $_history = $block->getOrder()->getVisibleStatusHistory() ?>
<?php if (count($_history)): ?>
    <div class="block block-order-details-comments">
		<div class="block-title--myac"><h3><?php /* @escapeNotVerified */ echo __('About Your Order') ?></h3></div>
        <div class="block-content">
            <div class="order-comments">
                <?php foreach ($_history as $_historyItem): ?>
                    <div class="comment">
						<div class="comment-content"><?php echo $block->escapeHtml($_historyItem->getComment()) ?></div>
						<div class="comment-date"><?php /* @escapeNotVerified */ echo $block->formatDate($_historyItem->getCreatedAt(), \IntlDateFormatter::MEDIUM, true) ?></div>
					</div>
                <?php endforeach; ?>
            </div>

        </div>
    </div>
<?php endif; ?>
