<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<?php
$_product = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
?>
<?php if($themeHelper->getStoreConfig('mpanel/product_details/wishlist') || $themeHelper->getStoreConfig('mpanel/product_details/compare')): ?>
	<div class="product-addto-links" data-role="add-to-links">
		<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $themeHelper->getStoreConfig('mpanel/product_details/wishlist')) : ?>
			<a href="#"
				class="action towishlist btn btn-default"
				data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
				data-action="add-to-wishlist"><i class="fa fa-heart"></i></a>
		<?php endif; ?>
		<?php if($themeHelper->getStoreConfig('mpanel/product_details/compare')): ?>
			<a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
				data-role="add-to-links"
				class="action tocompare btn btn-default"><i class="fa fa-random"></i></a>
		<?php endif ?>
	</div>
	<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $themeHelper->getStoreConfig('mpanel/product_details/wishlist')) : ?>
		<script type="text/x-magento-init">
			{
				"body": {
					"addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
				}
			}
		</script>
	<?php endif ?>
<?php endif ?>