<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php 
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field box-qty qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
			<span class="edit-qty minus" onclick="minusQty('qty')"><i class="fa fa-minus"></i></span>
			<input type="number"
						   name="qty"
						   id="qty"
						   maxlength="12"
						   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
						   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty form-control"
						   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
						   />
			<span class="edit-qty plus" onclick="plusQty('qty')"><i class="fa fa-plus"></i></span>
				
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart btn btn-secondary"
                    id="product-addtocart-button">
                <span class="text"><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
			<?php if($themeHelper->getStoreConfig('mpanel/product_details/wishlist') || $themeHelper->getStoreConfig('mpanel/product_details/compare') || $block->canEmailToFriend()): ?>
				<div class="product-addto-links" data-role="add-to-links">
					<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $themeHelper->getStoreConfig('mpanel/product_details/wishlist')) : ?>
						<a href="#"
							class="action towishlist btn btn-addlist"
							data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
							data-action="add-to-wishlist"><span class="icon"><span class="pe-7s-like"></span></a>
					<?php endif; ?>
					<?php if($themeHelper->getStoreConfig('mpanel/product_details/compare')): ?>
						<a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
							data-role="add-to-links"
							class="action tocompare btn btn-addlist"><span class="pe-7s-repeat"></span></a>
					<?php endif ?>
					<?php if ($block->canEmailToFriend()): ?>
						<a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
						   class="action mailto friend btn btn-addlist"><span class="pe-7s-mail-open"></span></a>
					<?php endif; ?>
				</div>
				<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $themeHelper->getStoreConfig('mpanel/product_details/wishlist')) : ?>
					<script type="text/x-magento-init">
						{
							"body": {
								"addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
							}
						}
					</script>
				<?php endif ?>
			<?php endif ?>
            <?php echo $block->getChildHtml('', true) ?>
			
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
<script type="text/javascript">
function plusQty(qtyInput){
	require([
	'jquery'
	], function(jQuery){
		(function($) {
			if($('#'+qtyInput).attr('disabled')!='disabled'){
				qty = $('#'+qtyInput).attr('value');
				qty = parseInt(qty);
				qty++;
				$('#'+qtyInput).val(qty);
			}
		})(jQuery);
	});
	
}
function minusQty(qtyInput){
	require([
	'jquery'
	], function(jQuery){
		(function($) {
			if($('#'+qtyInput).attr('disabled')!='disabled'){
				qty = $('#'+qtyInput).attr('value');
				qty = parseInt(qty);
				
				if(qty>1){
					qty--;
					$('#'+qtyInput).val(qty);
				}
			}
		})(jQuery);
	});
}
</script>