<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<div class="product-name">
	<span class="h1"><?php echo $_helper->productAttribute($block->getProduct(), $block->getProduct()->getName(), 'name') ?></span>
</div>
