<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="do" title="<?php /* @escapeNotVerified */ echo __('Update Wish List') ?>" class="action btn btn-default btn-lg  update">
        <span><?php /* @escapeNotVerified */ echo __('Update Wish List') ?></span>
    </button>
<?php endif;?>
