<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('product_page_settings/show_related_products_by_brand')): ?>
        <?php if ($brand = $block->getBrand()): ?>
            <?php
            $_productCollection = $block->getProductCollection();
            $_helper = $this->helper('Magento\Catalog\Helper\Output');
            ?>
            <?php if (count($_productCollection)): ?>
                <div class="brand-related-products">
                    <div class="block-title title">
                        <strong id="block-heading" role="heading" aria-level="2"><?php echo $block->getConfig('product_page_settings/title_related_products'); ?></strong>
                    </div>
                    <div class="block-content content" aria-labelledby="block-heading">
                        <div class="products wrapper grid products-grid products-related">
                            <ol class="products list items product-items">
                                <?php $iterator = 1; ?>
                                <?php foreach ($_productCollection as $_product): ?>
                                    <li class="item product product-item">
                                        <div class="product-item-info">
                                            <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo">
                                                <?php echo $block->getImage($_product, 'related_products_list')->toHtml(); ?>
                                            </a>
                                            <div class="product details product-item-details">
                                                <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>">
                                                        <?php echo $block->escapeHtml($_product->getName()) ?></a>
                                                </strong>
                                                <?php echo $block->getProductPrice($_product); ?>
                                                <?php echo $block->getReviewsSummaryHtml($_product, null) ?>
                                                <div class="product actions product-item-actions">
                                                    <div class="actions-primary">
                                                        <?php if ($_product->isSaleable()): ?>
                                                            <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_product) ?>"}}' type="button" title="<?php echo __('Add to Cart') ?>">
                                                                    <span><?php echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary"
                                                                        data-post='<?php echo $postData; ?>'
                                                                        type="button" title="<?php echo __('Add to Cart') ?>">
                                                                    <span><?php echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_product->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                            <a href="#" data-post='<?php echo $block->getAddToWishlistParams($_product); ?>' class="action towishlist" data-action="add-to-wishlist" title="<?php echo __('Add to Wish List') ?>">
                                                                <span><?php echo __('Add to Wish List') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($block->getAddToCompareUrl()): ?>
                                                            <?php
                                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                            ?>
                                                            <a href="#" class="action tocompare"
                                                               data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                                               data-role="add-to-links"
                                                               title="<?php echo __('Add to Compare'); ?>">
                                                                <span><?php echo __('Add to Compare') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach ?>
                            </ol>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
