<?php
$collection = $block->getCollection();
?>
<?php if (count($collection)): ?>
    <?php
    
    $title = $this->getData('title');	
    $numberOfPosts = $this->getData('number_of_posts');
    $showThumbnail = $this->getData('show_thumbnail');   
	$navigation = $this->getData('show_nav');
	$dots = $this->getData('show_dots');

	$autoPlay = $this->getData('auto_play');	
    $customClass = $this->getData('custom_class');
    ?>
	<div class="testimonial-container <?php echo $customClass;?>">
		<?php if( $title !=''): ?>
		<div class="carousel_wrapper">
			<div class="title">
				<h2><?php echo $title?></h2>
			</div>
		</div>
		<?php endif;?>
		<div class="testimonials-carousel">
		<?php foreach($collection as $_item): ?>
			<div class="testimonial-item row">
				<?php if($showThumbnail): ?>
				<div class="testimonial-author col-lg-3 col-md-3 col-sm-4 col-xs-6">
					<div class="img-author">
						<?php if($this->getAvatarUrl($_item->getAvatar())): ?>
							<img src="<?php echo $this->getAvatarUrl($_item->getAvatar()) ?>" alt="" class="img-responsive">
						<?php endif;?>
					</div>
				</div>
				<div class="testimonial-content col-lg-9 col-md-9 col-sm-8 col-xs-6">
					<p><?php echo $_item->getContent() ?></p>				
					<div class="author">
						<strong><?php echo $_item->getName() ?></strong>
						<span><?php echo $_item->getInformation();?></span>
					</div>
				</div>
				<?php else: ?>
				<div class="testimonial-content col-md-12 col-xs-12 ">
					<p><?php echo $_item->getContent() ?></p>				
					<div class="author">
						<strong><?php echo $_item->getName() ?></strong>
						<span><?php echo $_item->getInformation();?></span>
					</div>
				</div>
				<?php endif;?>
			</div>
		<?php endforeach;?>
		</div>
		
		<?php if($navigation !=''):?>
			<?php $navigation = true;?>
		<?php else: ?>
			<?php $navigation = false;?>
		<?php endif?>
		<?php if($dots !=''):?>
			<?php $dots = true;?>
		<?php else: ?>
			<?php $dots = false;?>
		<?php endif?>
		<?php if($autoPlay !=''):?>
			<?php $autoPlay = true;?>
		<?php else: ?>
			<?php $autoPlay = false;?>
		<?php endif?>
		
		<script type="text/javascript">
			require([
				'jquery',
				'mgs/owlcarousel'
			], function(jQuery){
				(function($) {
					$(".testimonials-carousel").owlCarousel({
						items: 1,
						animateOut:'fadeOut',
						animateIn:'fadeIn',
						smartSpeed: 800,
						loop: true,
						nav: <?php echo json_encode($navigation) ?>,
						dots: <?php echo json_encode($dots);?>,
						autoplay:<?php echo json_encode($autoPlay)?>,
						navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
						responsive:{
							0 : {items: 1},
							480 : {items: 1},
							768 : {items: 1},
							980 : {items:1},
							1200 : {items: 1}
						}
					});
				})(jQuery);
			});
		</script>
	</div>
	<?php else: ?>
	<div class="alert alert-danger">
		<?php echo __('No testimonial to show')?>
	</div>
<?php endif;?>

