<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currentCategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
$template =  preg_replace('/\D/', '', $themeHelper->checkLayoutPage($currentCategory)->getPageLayout());

$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <div class="top-toolbar"><?php echo $block->getToolbarHtml() ?></div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items products-<?php echo $viewMode;?> row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $i=0; foreach ($_productCollection as $_product): $i++; ?>
				<?php $_productType = $_product->getTypeID();?>
				<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
				<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
				<?php $size = $themeHelper->getImageSize(); ?>
				<?php $productImage = $block->getImage($_product, $image); ?>
                <?php $productImages = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
                <?php if ($pos != null) { $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"'; } ?>
				
				<?php if($viewMode == "grid"): ?>
					<li class="item product product-item <?php echo $themeHelper->getColClass($themeSettings['catalog']['per_row']) ?> <?php echo $themeHelper->getClearClass($themeSettings['catalog']['per_row'], $i) ?>">
						<div class="product-item-info product-content" data-container="product-grid">
							<div class="product-top">
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<img src="<?php echo $productImages; ?>" alt="<?php echo $_productNameStripped ?>" class="product-image-photo img-responsive"/>
									<?php //echo $productImage->toHtml(); ?>
								</a>
								<div class="button-quickview">
									<?php echo $quickViewHelper->aroundQuickViewHtml($_product);?>
								</div>
								<?php echo $themeHelper->getProductLabel($_product) ?>	
							</div>
							<div class="product details product-item-details product-desc">
								<div class="cate-name text-center">
									<div class="text">
										<span><?php echo $themeHelper->getCategoryName($_product,$this->getData('title'),'') ?></span>
									</div>
								</div>
								<h4 class="product-name">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
								   <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h4>
								<div class="rating-price">
									<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
								</div>
								<?php echo $block->getProductDetailsHtml($_product); ?>
								<div class="controls">
									<div class="add-to-cart hover-hidden">
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="btn btn-default action tocart">
													<span class="text">
													<?php if($_productType == 'simple'): ?>
														<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>
													<?php elseif($viewMode == 'grid'): ?>
														<?php /* @escapeNotVerified */ echo __('Select Option') ?>
													<?php else:  ?>
														<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>
													<?php endif;?>
													</span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									<?php if(!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>
										<div class="controls-hover">
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
											<button class="action towishlist btn btn-addlist" 		   
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<span class="pe-7s-like"></span>
											</button>
										<?php endif; ?>
										<?php if ($_product->isSaleable()): ?>
										<?php $postParams = $block->getAddToCartPostParams($_product); ?>
										<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
											<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
											<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
											<?php echo $block->getBlockHtml('formkey')?>
											<button type="submit"
													title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
													class="btn btn-addlist tocart action">												
												<?php if($_productType == 'simple'): ?>
													<span class="pe-7s-shopbag icon-shop"></span>
												<?php else:  ?>
													<span class="pe-7s-menu icon-menu"></span>	
												<?php endif;?>
											</button>
										</form>
										<?php endif;?>
										
										<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<?php if(!$themeSettings['catalog']['compare_button']): ?>
											<button class="action tocompare btn btn-addlist"
												aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
											   role="button">
												<span class="pe-7s-repeat"></span>
											</button>
										<?php endif ?>
										</div>
									<?php endif;?>
								</div>
							</div>
						</div>
					</li>
				<?php else: ?>
					<li class="item product product-item col-xs-12">
						<div class="product-item-info product-content" data-container="product-grid">
							<div class="row">
								<div class="<?php if($template == 1):?>col-md-3<?php else: ?>col-md-4<?php endif;?> col-sm-6 col-xs-12">
									<div class="product-top">
										<?php // Product Image ?>
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<img src="<?php echo $productImages; ?>" alt="<?php echo $_productNameStripped ?>" class="product-image-photo img-responsive"/>
											<?php //echo $productImage->toHtml(); ?>
										</a>
										<div class="button-quickview">
											<?php echo $quickViewHelper->aroundQuickViewHtml($_product);?>
										</div>
										<?php echo $themeHelper->getProductLabel($_product) ?>	
									</div>
								</div>
								<div class="<?php if($template == 1): ?>col-md-9<?php else: ?> col-md-8<?php endif;?> col-sm-6 col-xs-12">
									<div class="product details product-item-details product-desc">
										
										<h4 class="product-name">
											<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										   <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
											</a>
										</h4>
										<div class="cate-name text-left">
											<div class="text">
												<span><?php echo $themeHelper->getCategoryName($_product,$this->getData('title'),'') ?></span>
											</div>
										</div>
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
										<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
										
										<?php echo $block->getProductDetailsHtml($_product); ?>
										<div class="controls">
											<div class="add-to-cart">
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
														<button type="submit"
																title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																class="btn btn-default action tocart">
															<span class="text">
															<?php if($_productType == 'simple'): ?>
																<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>
															<?php elseif($viewMode == 'grid'): ?>
																<?php /* @escapeNotVerified */ echo __('Select Option') ?>
															<?php else:  ?>
																<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>
															<?php endif;?>
															</span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
											<?php if(!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>
												<ul class="icon-links">
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
														<li><button class="action towishlist btn btn-addlist" 		   
													   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
													   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
													   data-action="add-to-wishlist"
													   role="button">
														<span class="pe-7s-like"></span>
													</button></li>
													<?php endif;?>
													<?php if(!$themeSettings['catalog']['compare_button']): ?>
													<?php
													$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
													?>
													<li>
													<button class="action tocompare btn btn-addlist"
														aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
													   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
													   role="button">
														<span class="pe-7s-repeat"></span>
													</button>
													</li>
												<?php endif ?>
												</ul>
											<?php endif;?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</li>
				<?php endif ?>
            <?php endforeach; ?>
        </ol>
    </div>
	<div class="bottom-toolbar">
		<?php echo $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>