<?php $buttonTitle = __('More Details'); ?>
<div class="box-more-details">
    <div class="fieldset">
        <div class="actions">
            <a target="_parent" href="<?php /* @escapeNotVerified */ echo $this->getProduct()->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>" class="action primary" id="product-more-details-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </a>
        </div>
    </div>
</div>
