<?php 
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
	$themeSettings = $themeHelper->getThemeSettings();

	$image = 'category_page_grid';
	$showDescription = false;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	if($this->getProductsPerRow()){
		$perrow = $this->getProductsPerRow();
	}else{
		$perrow = $themeSettings['catalog']['per_row'];
	}
	$category = $this->getCategory();
?>
<?php $_productCollection = $this->getProductCollection($category); ?>
<?php if($_productCollection->count()): ?>
	<?php foreach ($_productCollection as $_product): ?>
		<li class="item product product-item <?php echo $themeHelper->getColClass($perrow) ?>">
			<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
			<div class="product-item-info product-content" data-container="product-grid">
				<div class="product-top">
					<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
						$size = $themeHelper->getImageSize();
						$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
					<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
						<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
						<?php echo $themeHelper->getProductLabel($_product) ?>
					</a>
				</div>
				
				<div class="product details product-item-details product-desc">
					<div class="top-desc">
						<div class="text-desc cate-name">
							<div class="text"><span>abc	</span></div>
						</div>
						<div class="controls">
							<?php if(!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>
								<ul data-role="add-to-links" class="actions-secondary">
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
										<li><a href="#"
										   class="action towishlist"
										   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
										   data-action="add-to-wishlist"
										   role="button">
											<i class="fa fa-heart-o"></i>
										</a></li>
									<?php endif; ?>
									<?php
									$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
									?>
									<?php if(!$themeSettings['catalog']['compare_button']): ?>
										<li><a href="#"
										   class="action tocompare"
										   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
										   role="button">
											<i class="fa fa-sliders"></i>
										</a></li>
									<?php endif ?>
								</ul>
							<?php endif ?>
						</div>
					</div>
					<p class="product name product-item-name">
						<a class="product-item-link"
						   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
							<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
						</a>
					</p>
					<?php if ($showDescription):?>
						<div class="product description product-item-description">
							<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="action more"><?php echo __('Learn More') ?></a>
						</div>
					<?php endif; ?>
					<?php echo $block->getProductDetailsHtml($_product); ?>
					<div class="desc-prd">
						<div class="information-prd">
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType,''); ?>
							<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
						</div>
						<div class="add-cart-item">
							<div class="product actions product-item-actions">
							<div class="actions-primary">
								<?php if ($_product->isSaleable()): ?>
									<?php $postParams = $block->getAddToCartPostParams($_product); ?>
									<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
										<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
										
										<?php echo $block->getBlockHtml('formkey')?>
										<button type="submit"
												title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>">
											<span><span class="fa fa-shopping-cart"></span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
										</button>
									</form>
								<?php else: ?>
									<?php if ($_product->getIsSalable()): ?>
										<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
									<?php endif; ?>
								<?php endif; ?>
							</div>
						</div>
						</div>
					</div>
				</div>
			</div>
		</li>
	<?php endforeach; ?>
		
<?php endif ?>