<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Upsell Products');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>
	<?php if($type =='related'):?>
		<div class="navigation-top-right block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
			
			<div class="block-title title">
				<h4 id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></h4>
			</div>
			<?php $_collectionSize = count($items);?>
			<div class="block-content content">
				<?php if ($type == 'related' && $canItemsAddToCart): ?>
				<div class="block-actions">
					<?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
					<button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
				</div>
				<?php endif; ?>
				<div id="related_sidebar" class="product-list-block products wrapper grid products-<?php /* @escapeNotVerified */ echo $type; ?><?php if(count($items) > 3): ?> owl-carousel <?php endif;?>">
					<?php $i=0; foreach($items as $_item): $i++; ?>
						<?php 
							$_itemNameStripped = $block->stripTags($_item->getName(), null, true);
							$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
							$size = $themeHelper->getImageSize();
							$productImage = $_imagehelper->init($_item, $image)->resize($size['width'], $size['height'])->getUrl();        
						?>
						<?php $available = ''; ?>
							<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
								<?php if (!$_item->getRequiredOptions()): ?>
									<?php $available = 'related-available'; ?>
								<?php endif; ?>
							<?php endif; ?>
						<?php if($i % 3 == 1):?>
							<div class="product-list products-grid slider">
						<?php endif;?>
								<div class="item">
									<div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?> product-content">
										<div class="product-top product-left">
											<img src="<?php echo $productImage;?>" alt="<?php echo $_itemNameStripped?>" class="img-responsive"/>
											<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
												<?php if (!$_item->getRequiredOptions()): ?>
													<div class="field choice related">
														<input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
														
													</div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
										<div class="product-desc product-right">
											<h4 class="product-name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
												<?php echo $block->escapeHtml($_item->getName()) ?></a>
											</h4>
											<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
											<?php if ($templateType): ?>
												<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>
											<?php endif; ?>
											
											<?php if ($showWishlist || $showCompare || $showCart): ?>
											<div class="controls">
												<div class="add-to-cart hover-hidden">
													<?php if ($showCart): ?>													
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<button class="btn btn-default" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																</button>
															<?php else: ?>
																<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																?>
																<button class="btn btn-default"
																		data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																</button>
															<?php endif; ?>
														<?php else: ?>
															<?php if ($_item->getIsSalable()): ?>
																<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>													
												<?php endif; ?>
												</div>
												<div class="controls-hover">
													<?php if($showCart): ?>
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<button class="btn btn-addlist tocart" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="pe-7s-menu"></span>
																</button>
															<?php else: ?>
																<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																?>
																<button class="btn btn-addlist tocart"
																		data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="pe-7s-shopbag"></span>
																</button>
															<?php endif; ?>
														<?php endif;?>
													<?php endif?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
														<button data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist btn btn-addlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
															<span class="pe-7s-like"></span>
														</button>
													<?php endif; ?>
													<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
													<?php
														$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
														?>
														<button class="action tocompare btn btn-addlist"
														   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
														   data-role="add-to-links"
														   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
															<span class="pe-7s-repeat"></span>
														</button>
													<?php endif; ?>
												</div>
											</div>
											<?php endif;?>
										</div>
									</div>
								</div>
						<?php if(($i % 3 == 0)||($i == $_collectionSize)): ?>
							</div>
						<?php endif;?>
					<?php endforeach;?>
				</div>
				<?php if($_collectionSize > 3): ?>
						<script type="text/javascript">
							require([
								'jquery',
								'mgs/owlcarousel'
							], function(jQuery){
								(function($) {
								$("#related_sidebar").owlCarousel({
									items : 1,
									lazyLoad : true,
									nav : true,
									dots : false,
									loop: false,
									autoPlay: false,
									stopOnHover: false,
									navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
									responsive:{
										0 : {items: 1}, 480 : {items: 1}, 768 : {items: 1}, 980 : {items: 1}, 1200 : {items: 1}
									}
								});
								})(jQuery);
							});
						</script>
				<?php endif ?>
			</div>
		</div>
	<?php else: ?>
		<?php if($type =='upsell'): ?>
			<div class="block <?php /* @escapeNotVerified */ echo $class; ?> navigation-top-right border-title padding-bottom60" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?> ">
		<?php else: ?>
			<div class="block navigation-top-right border-title<?php /* @escapeNotVerified */ echo $class; ?> padding-bottom60">
		<?php endif;?>
			<div class="block-title title">
				<h3 id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></h3>
			</div>
			
			<div class="block-content content">		
				<div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
					<ol class="products list items product-items" id="block-<?php echo $type?>-<?php echo $block->getId();?>">
						<?php $iterator = 1; ?>
						<?php foreach ($items as $_item): ?>
							<?php $available = ''; ?>
							<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
								<?php if (!$_item->getRequiredOptions()): ?>
									<?php $available = 'related-available'; ?>
								<?php endif; ?>
							<?php endif; ?>
							<?php 
								$_itemNameStripped = $block->stripTags($_item->getName(), null, true);
								$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
								$size = $themeHelper->getImageSize();
								$productImage = $_imagehelper->init($_item, $image)->resize($size['width'], $size['height'])->getUrl();        
							?>
							<li class="item">
								<div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?> product-content">
									<div class="product-top product-left">
										<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
											<img src="<?php echo $productImage;?>" class="img-responsive" alt="<?php echo $_itemNameStripped?>"/>
										</a>
										<div class="button-quickview">
											<?php echo $quickViewHelper->aroundQuickViewHtml($_item);?>
										</div>
										<?php echo $themeHelper->getProductLabel($_item) ?>	
									</div>
									<div class="product-desc product-right">
										<h4 class="product-name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
											<?php echo $block->escapeHtml($_item->getName()) ?></a>
										</h4>
										<div class="rating-price">
										<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
										<?php if ($templateType): ?>
											<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>
										<?php endif; ?>
										</div>
										
										<?php if ($showWishlist || $showCompare || $showCart): ?>
											<div class="controls">
												<div class="add-to-cart hover-hidden">
													<?php if ($showCart): ?>											
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<button class="btn btn-default" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																</button>
															<?php else: ?>
																<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																?>
																<button class="btn btn-default"
																		data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																</button>
															<?php endif; ?>
														<?php else: ?>
															<?php if ($_item->getIsSalable()): ?>
																<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>													
												<?php endif; ?>
												</div>
												<div class="controls-hover">
													<?php if($showCart): ?>
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<button class="btn btn-addlist tocart" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="pe-7s-menu"></span>
																</button>
															<?php else: ?>
																<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																?>
																<button class="btn btn-addlist tocart"
																		data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="pe-7s-shopbag"></span>
																</button>
															<?php endif; ?>
														<?php endif;?>
													<?php endif?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
														<button data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist btn btn-addlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
															<span class="pe-7s-like"></span>
														</button>
													<?php endif; ?>
													<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
													<?php
														$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
														?>
														<button class="action tocompare btn btn-addlist"
														   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
														   data-role="add-to-links"
														   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
															<span class="pe-7s-repeat"></span>
														</button>
													<?php endif; ?>
												</div>
											</div>
										<?php endif;?>
									</div>
								</div>
							</li>
						<?php endforeach;?>
					</ol>
					<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function(jQuery){
						(function($) {
						$("#block-<?php echo $type;?>-<?php echo $block->getId(); ?>").owlCarousel({
							items : 4,
							lazyLoad : true,
							loop: false,
							nav : true,
							dots : false,
							autoPlay: false,
							stopOnHover: false,
							margin: 30,
							navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
							responsive:{
								0 : {items: 1}, 480 : {items: 2}, 768 : {items: 2}, 980 : {items: 3}, 1200 : {items: 4}
							}
						});
						})(jQuery);
					});
				</script>
				</div>
			</div>
			
			</div>
	<?php endif;?>
	<!---------------------->
    
<?php endif;?>
