<?php $helper = $this->helper('MGS\Social\Helper\Data'); ?>
<?php if ($helper->getConfig('facebook_settings/active') && $helper->getConfig('facebook_page_plugin_settings/active')): ?>
<?php $appId = $helper->getConfig('facebook_settings/client_id'); ?>
    <div id="fb-root"></div>
	 <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '<?php echo $appId; ?>',
                xfbml: true,
                version: 'v2.4'
            });
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {
                return;
            }
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
<?php endif; ?>