<?php
$helper = $this->helper('MGS\Blog\Helper\Data');
$post = $block->getCurrentPost();
$collection = $block->getCollection();
?>
<?php if (count($collection)): ?>
    <div class="comment-list">
        <div class="comment-list-container">
            <?php foreach ($collection as $comment): ?>
                <div class="item">
                    <h4 class="name"><?php echo $comment->getName(); ?></h4>
                    <div class="content"><?php echo $comment->getContent(); ?></div>
                    <div class="posted-on"><?php echo __('Posted On: %1', $block->formatDate($comment->getCreatedAt(), \IntlDateFormatter::MEDIUM, false)); ?></div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="blog-post-comment-list-toolbar toolbar"><?php echo $block->getPagerHtml(); ?></div>
    </div>
<?php endif; ?>
