<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('product_page_settings/show_brand')): ?>
        <?php if ($brand = $block->getBrand()): ?>
            <?php
            if ($block->getConfig('product_page_settings/small_image_width') != '') {
                $width = $block->getConfig('product_page_settings/small_image_width');
            } else {
                $width = 240;
            }
            if ($block->getConfig('product_page_settings/small_image_height') != '') {
                $height = $block->getConfig('product_page_settings/small_image_height');
            } else {
                $height = 180;
            }
            ?>
            <div class="product-brand">
                <?php
                $img = '';
                if ($img = $brand->getSmallImageUrl()) { ?>
                    <div class="brand-image">
                        <a title="<?php echo $brand->getName(); ?>" href="<?php echo $brand->getUrl(); ?>"><img width="<?php echo $width; ?>" height="<?php echo $height; ?>" src="<?php echo $img; ?>" alt="<?php echo $brand->getName(); ?>" class="image img-responsive"/></a>
                    </div>
                <?php } ?>
              
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
