<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php
$_itemCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
?>
<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'category_page_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;	
    $description = false;
?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title):?>
        <div class="block-title col-md-12 col-sm-12 col-xs-12">
            <h3><?php /* @escapeNotVerified */ echo $title; ?></h3>
        </div>
        <?php endif ?>
        <div class="block-content col-md-12 col-sm-12 col-xs-12">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="row products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php  $iterator = 1; ?>
                    <?php $i=0; foreach ($items as $_item): $i++; ?>
                        <li class="item <?php echo $themeHelper->getColClass($themeSettings['catalog']['per_row']) ?> <?php echo $themeHelper->getClearClass($themeSettings['catalog']['per_row'], $i) ?>">
						<?php
							$_itemNameStripped = $block->stripTags($_item->getName(), null, true);
						?>
                        <div class="product-item-info product-content">
							<div class="product-top">
								<?php
								$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
								$size = $themeHelper->getImageSize();
								$productImage = $_imagehelper->init($_item, $image)->resize($size['width'], $size['height'])->getUrl();
								
								?>
								<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">                                
									<img src="<?php echo $productImage; ?>" alt="<?php echo $_itemNameStripped ?>" class="img-responsive"/>
									
								</a>
								
								<div class="button-quickview">
									<?php echo $quickViewHelper->aroundQuickViewHtml($_item); ?>
								</div>
								<?php echo $themeHelper->getProductLabel($_item) ?>
							</div>
							<div class="product-item-details product-desc">
								<div class="cate-name text-center"><div class="text"><span><?php echo $themeHelper->getCategoryName($_item,$this->getData('title'),'') ?></span></div></div>
								<h4 class="product-name product-item-name">
									<a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo $_itemNameStripped ?>"><?php echo $_item->getName() ?></a>
								</h4>
								<div class="rating-price">
									<?php
									echo $block->getProductPriceHtml($_item, $type);
									?>
									<?php if ($templateType): ?>
										<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>
									<?php endif; ?>
								</div>
								<?php if ($showWishlist || $showCompare || $showCart): ?>
									<div class="controls">
										<?php if ($showCart): ?>
											<div class="add-to-cart hover-hidden">
												<?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary btn btn-default"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary btn btn-default"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
											</div>
										<?php endif;?>
										<?php if(!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>
											<?php if ($showWishlist || $showCompare): ?>
												<div class="controls-hover">
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist && !$themeSettings['catalog']['wishlist_button']): ?>
                                                    <button                                                    data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                       class="action towishlist btn btn-addlist" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                        <span class="pe-7s-like"></span>
                                                    </button>
													<?php endif; ?>
													<?php if($showCart): ?>
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<button class="action tocart primary btn btn-addlist"
																		data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="pe-7s-menu"></span>
																</button>
															<?php else: ?>
																<?php
																	$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																	$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																?>
																<button class="action tocart primary btn btn-addlist"
																		data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span class="pe-7s-shopbag"></span>
																</button>
															<?php endif; ?>
														<?php endif;?>
													<?php endif;?>
													
													<?php if ($block->getAddToCompareUrl() && $showCompare && !$themeSettings['catalog']['compare_button']): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <button class="action tocompare btn btn-addlist"
                                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                        <i class="pe-7s-repeat"></i>
                                                    </button>
                                                <?php endif; ?>
												</div>
											<?php endif;?>
										<?php endif;?>
									</div>
								<?php endif;?>
							</div>
							
                        </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
