<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a class="action action-edit margin-left10"
       href="<?php /* @escapeNotVerified */ echo $block->getConfigureUrl() ?>"
       title="<?php echo $block->escapeHtml(__('Edit item parameters')); ?>">
        <span>
            <?php /* @escapeNotVerified */ //echo __('Edit') ?>
			<i class="fa fa-pencil"></i>
        </span>
   </a>
<?php endif ?>
