<?php $block = $this->getBlock() ?>
<?php $welcomeMessage = $block->getWelcome(); ?>

<?php echo $block->getChildHtml('store_language') ?>
<?php echo $block->getChildHtml('currency') ?>

<div class="greet welcome" data-bind="scope: 'customer'">
	<span data-bind="text: customer().fullname ? $t('Welcome, %1!').replace('%1', customer().fullname) : '<?php echo $block->escapeHtml($welcomeMessage) ?>'"><?php echo $block->escapeHtml($welcomeMessage) ?></span>
</div>
			
<?php echo $block->getChildHtml('top.links') ?>
<?php echo $block->getChildHtml('logo') ?>
<?php echo $block->getChildHtml('topSearch') ?>
<?php echo $block->getChildHtml('minicart') ?>
<?php echo $block->getChildHtml('megamenu') ?>