<?php $block = $this->getBlock() ?>
<?php $welcomeMessage = $block->getWelcome(); ?>
<div class="top-header-content">
	<div class="container">
		<div class="row">
			<div class="col-md-5 col-sm-6 dol-xs-12">
				<?php echo $block->getChildHtml('store_language') ?>
				<?php echo $block->getChildHtml('currency') ?>
				<div class="greet welcome" data-bind="scope: 'customer'">
					<span data-bind="text: customer().fullname ? $t('Welcome, %1!').replace('%1', customer().fullname) : '<?php echo $block->escapeHtml($welcomeMessage) ?>'"><?php echo $block->escapeHtml($welcomeMessage) ?></span>
				</div>
			</div>
			<div class="col-md-7 col-sm-6 dol-xs-12">
				<?php echo $block->getChildHtml('top.links') ?>
			</div>
		</div>
	</div>
</div>
<div class="middle-header-content">
	<div class="container">
		<div class="row">
			<div class="col-md-2 col-sm-2 col-xs-12"><?php echo $block->getChildHtml('logo') ?></div>
			<div class="col-md-8 col-sm-8 col-xs-6"><?php echo $block->getChildHtml('topSearch') ?></div>
			<div class="col-md-2 col-sm-2 col-xs-6 cart-mobile"><?php echo $block->getChildHtml('minicart') ?></div>
		</div>
	</div>
</div>
<?php echo $block->getChildHtml('megamenu') ?>